# Generated by Django 5.1 on 2024-08-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('last_7_day_sale', models.IntegerField()),
                ('fit', models.CharField(blank=True, max_length=255, null=True)),
                ('fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('neck', models.CharField(blank=True, max_length=255, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=255, null=True)),
                ('pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_skus', to='products.product')),
            ],
        ),
    ]
